"""reservation table

Revision ID: 0c555ff42d00
Revises: 
Create Date: 2019-01-28 09:54:08.540962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c555ff42d00'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('confirmation', sa.String(length=10), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=True),
    sa.Column('company', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.String(length=10), nullable=True),
    sa.Column('end_date', sa.String(length=10), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservation_confirmation'), 'reservation', ['confirmation'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservation_confirmation'), table_name='reservation')
    op.drop_table('reservation')
    # ### end Alembic commands ###
